import os
from jinja2 import Environment, FileSystemLoader

def format_rfc2822(date_str):
    # For now, we assume the date_str is already in RFC 2822 format 
    # as generated by create_episode.
    return date_str

def format_duration(seconds):
    hours = seconds // 3600
    minutes = (seconds % 3600) // 60
    seconds = seconds % 60
    if hours > 0:
        return f"{hours:02d}:{minutes:02d}:{seconds:02d}"
    else:
        return f"{minutes:02d}:{seconds:02d}"

def render_feed_xml(template_dir, podcast_config, episodes):
    env = Environment(loader=FileSystemLoader(template_dir))
    template = env.get_template('feed.xml.j2')
    return template.render(podcast=podcast_config, episodes=episodes)

def render_index_html(template_dir, podcast_config, episodes):
    env = Environment(loader=FileSystemLoader(template_dir))
    template = env.get_template('index.html.j2')
    return template.render(podcast=podcast_config, episodes=episodes)

def generate_site(template_dir, podcast_config, episodes, docs_dir):
    feed_xml = render_feed_xml(template_dir, podcast_config, episodes)
    index_html = render_index_html(template_dir, podcast_config, episodes)
    
    with open(os.path.join(docs_dir, 'feed.xml'), 'w') as f:
        f.write(feed_xml)
    
    with open(os.path.join(docs_dir, 'index.html'), 'w') as f:
        f.write(index_html)
